version: '3.8'

services:
  distcache-node1:
    build: .
    container_name: distcache-node1
    ports:
      - "6379:6379"
      - "8080:8080"
    volumes:
      - node1_data:/data
    environment:
      - NODE_ID=node-1
      - CLUSTER_NODES=distcache-node1,distcache-node2,distcache-node3
    networks:
      - distcache-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "sh", "-c", "echo 'PING' | nc -w 1 localhost 6379 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  distcache-node2:
    build: .
    container_name: distcache-node2
    ports:
      - "6380:6379"
      - "8081:8080"
    volumes:
      - node2_data:/data
    environment:
      - NODE_ID=node-2
      - CLUSTER_NODES=distcache-node1,distcache-node2,distcache-node3
    networks:
      - distcache-net
    restart: unless-stopped
    depends_on:
      - distcache-node1
    healthcheck:
      test: ["CMD", "sh", "-c", "echo 'PING' | nc -w 1 localhost 6379 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  distcache-node3:
    build: .
    container_name: distcache-node3
    ports:
      - "6381:6379"
      - "8082:8080"
    volumes:
      - node3_data:/data
    environment:
      - NODE_ID=node-3
      - CLUSTER_NODES=distcache-node1,distcache-node2,distcache-node3
    networks:
      - distcache-net
    restart: unless-stopped
    depends_on:
      - distcache-node1
    healthcheck:
      test: ["CMD", "sh", "-c", "echo 'PING' | nc -w 1 localhost 6379 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  node1_data:
  node2_data:
  node3_data:

networks:
  distcache-net:
    driver: bridge